import { ClerkProvider } from "@/components/clerk-provider";
import { Header } from "@/components/header";
import { ThemeProvider } from "@/components/theme-provider";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

const HEADER_HEIGHT = "4rem";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <ClerkProvider>
        <html lang="en" className="h-full" suppressHydrationWarning>
          <body
            className={`${geistSans.variable} ${geistMono.variable} flex min-h-full flex-col antialiased`}
            style={
              {
                "--header-height": HEADER_HEIGHT,
              } as React.CSSProperties
            }
          >
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <div className="flex h-full w-full flex-col">
                <div className="fixed top-0 left-0 right-0 z-50">
                  <Header />
                </div>
                <div className="flex flex-1 pt-14 h-full">
                  <div className="h-[calc(100vh-4rem)] sticky top-16">
                    <AppSidebar />
                  </div>
                  <main className="flex-1 overflow-auto">{children}</main>
                </div>
              </div>
            </ThemeProvider>
          </body>
        </html>
      </ClerkProvider>
    </SidebarProvider>
  );
}
